name: DoltCli

# Controls when the workflow will run
on:

  push:
    branches: [ "main" ]

  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'
        
      - name: Login dolt
        run: | 
          dolt config --global --add user.email ${{secrets.DOLT_USER_EMAIL}}
          dolt config --global --add user.name ${{secrets.DOLT_USER_NAME}}
          # dolt config --global --add user.creds ${{secrets.DOLT_USER_CREDS}}
          # dolt creds new
          dolt config --global --add user.creds j2mn4kt3263mr6ba0rcs006aae9jl84hs5jem70kpjjqg
          mkdir -p ~/.dolt/creds/
          # echo "${{secrets.DOLT_USER_CREDS_FILE}}" > ~/.dolt/creds/${{secrets.DOLT_USER_CREDS}}.jwk
          echo '{"d":"-Q2Uv01qYb0CXrJi_R3aOti7EjJ8tFAPAlOLNZZ_Lbc=","x":"h6MGUYJN2RF_EGbwu0mfCZfr2Vuqwe5x8l1pXEyErN_5DZS_TWphvQJesmL9Hdo62LsSMny0UA8CU4s1ln8ttw==","kty":"OKP","crv":"Ed25519"}' > ~/.dolt/creds/j2mn4kt3263mr6ba0rcs006aae9jl84hs5jem70kpjjqg.jwk
          cat $(ls ~/.dolt/creds/*)
          # dolt login ${{secrets.DOLT_CREDENTIAL}}
          dolt login v46p9fqdd9grq0ium9hfq7eq7bcbm4hifiq503o2ae5jb5jv5mrg
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          dolt clone hzuika/Test
          cd Test
          echo test, and deploy your project.
          
          dolt sql -q "show databases;"
          dolt sql -q "INSERT INTO Table_A VALUES ('title actions', 'name actions')";
          dolt sql -q "select * from Table_A"
          dolt add .
          dolt commit -m "from actions"
          dolt branch
          dolt push origin main
